services:
  postgres:
    image: postgres:17
    container_name: backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpbank-network

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - ./mcp_server/.env
    depends_on:
      - postgres
    networks:
      - vpbank-network

  agentify_backend:
    build:
      context: ./agentify_backend
      dockerfile: Dockerfile
    container_name: agentify-backend
    restart: unless-stopped
    ports:
      - 3002:3002
    env_file:
      - ./agentify_backend/.env
    depends_on:
      - mcp_server
    networks:
      - vpbank-network

  agentify_web:
    build:
      context: ./agentify-web
      dockerfile: Dockerfile
    container_name: agentify-web
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./agentify-web/.env
    depends_on:
      - agentify_backend
      - mcp_server
    networks:
      - vpbank-network

volumes:
  postgres_data:
    driver: local
    name: vpbank-postgres-data

networks:
  vpbank-network:
    driver: bridge
    name: vpbank-network
